version: "3.8"

services:
  frontend:
    image: frontend
    container_name: frontend_debug
    restart: always
    build:
      context: .
      dockerfile: next_app/Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - RUN_MODE=development
      - NEXT_PUBLIC_DEV_API_URL=<url> # change
      - NEXT_PUBLIC_DEV_UPLOADS_URL=<url/media/> # change
      - NEXT_PUBLIC_DEV_UPLOADS_MARKDOWN_URL=<admin_url> # change
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`<domain>`)" # change local IP addres
      # middlewares
      - "traefik.http.routers.nextjs.middlewares=frontend_auth"
      # https://doc.traefik.io/traefik/middlewares/http/basicauth/
      - "traefik.http.middlewares.frontend_auth.basicauth.users=dev:$$apr1$$LXRVA1AY$$2QKt3r0Z5OJKThIWHx/p1/" # dev:dev
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true